### ISSUE TITLE
[Bug] Renaming tool not working

### ISSUE THREAD

**Issue by Auriny** [Rapha149/ArmorStandEditor#7]
### Plugin version

1.5.7

### Server software and version

Purpur 1.21

### Steps to reproduce

```bash
1. Open the Armor Stand Editor
2. Try to rename the armor stand
3. See the [ArmorStandEditor] Task #2215 for ArmorStandEditor v1.5.7 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.inventory.CraftInventoryView de.rapha149.armorstandeditor.anvilgui.version.Wrapper1_21_R1$AnvilContainer.getBukkitView()'``` error in console
```

### Expected behaviour

I should see the anvil GUI

### What is actually happening?

When I click the rename button nothing happens

### Relevant log output

[10:11:08 WARN]: [ArmorStandEditor] Task #2215 for ArmorStandEditor v1.5.7 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.inventory.CraftInventoryView de.rapha149.armorstandeditor.anvilgui.version.Wrapper1_21_R1$AnvilContainer.getBukkitView()'
        at ArmorStandEditor (1).jar/de.rapha149.armorstandeditor.anvilgui.version.Wrapper1_21_R1$AnvilContainer.getBukkitInventory(Wrapper1_21_R1.java:149) ~[ArmorStandEditor (1).jar:?]
        at ArmorStandEditor (1).jar/de.rapha149.armorstandeditor.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:212) ~[ArmorStandEditor (1).jar:?]
        at ArmorStandEditor (1).jar/de.rapha149.armorstandeditor.anvilgui.AnvilGUI.access$1000(AnvilGUI.java:38) ~[ArmorStandEditor (1).jar:?]
        at ArmorStandEditor (1).jar/de.rapha149.armorstandeditor.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:712) ~[ArmorStandEditor (1).jar:?]
        at ArmorStandEditor (1).jar/de.rapha149.armorstandeditor.pages.SettingsPage.lambda$setRenameItem$18(SettingsPage.java:342) ~[ArmorStandEditor (1).jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1762) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Rapha149** [comment]
Thanks for reporting the bug!
The problem was that the dependency I use for opening the anvil inventory ([AnvilGUI](https://github.com/WesJD/AnvilGUI)) needed an update to work with 1.21.1. The update for my plugin is published on Spigot.
